name: J5 Get Malay Translation files

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  get-malay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout core-translations repo
        uses: actions/checkout@v4

      - name: Download Malay Joomla 6 language package
        run: |
          wget https://github.com/zakiabdullah/joomla-ms-MY/archive/refs/heads/j6.zip
          unzip j5.zip

      - name: Copy language files
        run: |
          mkdir -p translations/ms-MY/j5
          cp -r joomla-ms-MY-j5/* translations/ms-MY/j5/

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update Malay translation files (J5)" || echo "No changes"
          git push